device:
  vendor: google_devices

filters:
  files:
    match:
      - product/app/DevicePolicyPrebuilt/DevicePolicyPrebuilt.apk
      - product/app/DeviceStatisticsService/DeviceStatisticsService.apk
      - product/app/DiagnosticsToolPrebuilt/DiagnosticsToolPrebuilt.apk
      - product/app/MarkupGoogle/MarkupGoogle.apk
      - product/app/MicropaperPrebuilt/MicropaperPrebuilt.apk
      - product/app/NgaResources/NgaResources.apk
      - product/app/PixelThemesStub/PixelThemesStub.apk
      - product/app/PrebuiltGoogleTelemetryTvp/PrebuiltGoogleTelemetryTvp.apk
      - product/app/SafetyRegulatoryInfo/SafetyRegulatoryInfo.apk
      - product/app/SoundAmplifierPrebuilt/SoundAmplifierPrebuilt.apk
      - product/app/SoundPickerPrebuilt/SoundPickerPrebuilt.apk
      - product/app/VoiceAccessPrebuilt/VoiceAccessPrebuilt.apk
      - product/etc/permissions/com.google.android.apps.diagnosticstool.xml
      - product/etc/permissions/com.google.android.apps.dreamliner.xml
      - product/etc/permissions/com.google.android.hardwareinfo.xml
      - product/etc/permissions/com.google.android.odad.xml
      - product/etc/sysconfig/dreamliner.xml
      - product/framework/libhwinfo.jar
      - product/priv-app/AmbientSensePrebuilt/AmbientSensePrebuilt.apk
      - product/priv-app/BetaFeedback/BetaFeedback.apk
      - product/priv-app/BetterBug/BetterBug.apk
      - product/priv-app/CarrierMetrics/CarrierMetrics.apk
      - product/priv-app/DiagnosticsToolPrebuilt/DiagnosticsToolPrebuilt.apk
      - product/priv-app/HardwareInfo/HardwareInfo.apk
      - product/priv-app/HelpRtcPrebuilt/HelpRtcPrebuilt.apk
      - product/priv-app/MaestroPrebuilt/MaestroPrebuilt.apk
      - product/priv-app/OdadPrebuilt/OdadPrebuilt.apk
      - product/priv-app/OTAConfigNoZeroTouchPrebuilt/OTAConfigNoZeroTouchPrebuilt.apk
      - product/priv-app/PixelLiveWallpaperPrebuilt/PixelLiveWallpaperPrebuilt.apk
      - product/priv-app/SafetyHubPrebuilt/SafetyHubPrebuilt.apk
      - product/priv-app/SCONE/SCONE.apk
      - product/priv-app/SecurityHubPrebuilt/SecurityHubPrebuilt.apk
      - product/priv-app/SettingsIntelligenceGooglePrebuilt/SettingsIntelligenceGooglePrebuilt.apk
      - product/priv-app/Showcase/Showcase.apk
      - product/priv-app/ScribePrebuilt/ScribePrebuilt.apk
      - product/priv-app/TipsPrebuilt/TipsPrebuilt.apk
      - product/priv-app/TurboPrebuilt/TurboPrebuilt.apk
      - system_ext/app/EmergencyInfoGoogleNoUi/EmergencyInfoGoogleNoUi.apk
      - system_ext/app/Flipendo/Flipendo.apk
      - system_ext/etc/init/init.sota.rc
      - system_ext/etc/permissions/com.google.android.factoryota.xml
      - system_ext/priv-app/FactoryOta/FactoryOta.apk
      - system_ext/priv-app/GoogleFeedback/GoogleFeedback.apk
      - system_ext/priv-app/NexusLauncherRelease/NexusLauncherRelease.apk
      - system_ext/priv-app/OsloFeedback/OsloFeedback.apk
      - system_ext/priv-app/PixelSetupWizard/PixelSetupWizard.apk
      - system_ext/priv-app/QuickAccessWallet/QuickAccessWallet.apk
      - system_ext/priv-app/SettingsGoogle/SettingsGoogle.apk
      - system_ext/priv-app/StorageManagerGoogle/StorageManagerGoogle.apk
      - system_ext/priv-app/SystemUIGoogle/SystemUIGoogle.apk
      - system_ext/priv-app/UvExposureReporter/UvExposureReporter.apk
      - system_ext/priv-app/WallpaperPickerGoogleRelease/WallpaperPickerGoogleRelease.apk
      - system_ext/priv-app/YadaYada/YadaYada.apk
      - vendor/etc/default-permissions/default-permissions_talkback.xml

    prefix:
      - product/tts/google/
      - product/wallpaper/
      - product/app/PixelWallpapers
      - product/app/WallpapersBReel
      - product/etc/security/
      - product/priv-app/Dreamliner
      - product/priv-app/GoogleCamera/
      - system_ext/priv-app/FactoryOtaPrebuilt/
      - system_ext/priv-app/TurboAdapter/

  overlay_keys:
    match:
      - android:array/config_notificationMsgPkgsAllowedAsConvos
      - android:bool/config_enableFusedLocationOverlay
      - android:bool/config_enableGeocoderOverlay
      - android:bool/config_enableGeofenceOverlay
      - android:bool/config_enableGeolocationTimeZoneDetection
      - android:bool/config_enableNetworkLocationOverlay
      - android:bool/config_enablePrimaryLocationTimeZoneProvider
      - android:bool/config_enableSecondaryLocationTimeZoneProvider
      - android:bool/config_bugReportHandlerEnabled
      - android:bool/config_defaultRingtonePickerEnabled
      - android:bool/config_pinnerHomeApp
      - android:bool/config_profcollectReportUploaderEnabled
      - android:bool/config_sendPackageName
      - android:bool/config_showGesturalNavigationHints
      - android:bool/config_smart_battery_available
      - android:bool/config_swipe_up_gesture_setting_available
      - android:bool/config_volumeAdjustmentForRemoteGroupSessions
      - android:bool/config_volumeHushGestureEnabled
      - android:bool/config_volumeShowRemoteSessions
      - android:dimen/config_highResTaskSnapshotScale
      - android:integer/config_defaultNightMode
      - android:integer/config_storageManagerDaystoRetainDefault
      - android:string/android_start_title
      - android:string/android_upgrading_title
      - android:string/config_batterySaverScheduleProvider
      - android:string/config_defaultAccessibilityService
      - android:string/config_defaultAppPredictionService
      - android:string/config_defaultAssistantAccessComponent
      - android:string/config_defaultAutofillService
      - android:string/config_defaultDialer
      - android:string/config_defaultGallery
      - android:string/config_defaultListenerAccessPackages
      - android:string/config_defaultAugmentedAutofillService
      - android:string/config_defaultBugReportHandlerApp
      - android:string/config_defaultContentCaptureService
      - android:string/config_defaultModuleMetadataProvider
      - android:string/config_defaultMusic
      - android:string/config_defaultMusicRecognitionService
      - android:string/config_defaultProfcollectReportUploaderAction
      - android:string/config_defaultProfcollectReportUploaderApp
      - android:string/config_defaultSms
      - android:string/config_defaultTextClassifierPackage
      - android:string/config_deviceProvisioningPackage
      - android:string/config_emergency_dialer_package
      - android:string/config_incidentReportApproverPackage
      - android:string/config_powerSaveModeChangedListenerPackage
      - android:string/config_recentsComponentName
      - android:string/config_retailDemoPackage
      - android:string/config_retailDemoPackageSignature
      - android:string/config_secondaryHomePackage
      - android:string/config_secondaryLocationTimeZoneProviderPackageName
      - android:string/config_servicesExtensionPackage
      - android:string/default_wallpaper_component
      - android:string/harmful_app_warning_title
      - android:string-array/config_accessibility_allowed_install_source
      - android:string-array/config_allowedSecureInstantAppSettings
      - android:string-array/config_batteryPackageTypeService
      - android:string-array/config_defaultFirstUserRestrictions
      - android:string-array/config_disabledUntilUsedPreinstalledImes
      - android:string-array/config_highRefreshRateBlacklist
      - android:string-array/config_keep_warming_services
      - android:string-array/config_restrictedImagesServices
      - com.android.phone:string-array/config_countries_to_enable_shortcut_view
      - com.android.phone:string/dialer_default_class
      - com.android.providers.contacts:string/metadata_sync_pacakge
      - com.android.server.telecom:string/call_diagnostic_service_package_name
      - com.android.server.telecom:bool/config_hspa_data_distinguishable
      - com.android.server.telecom:string/dialer_default_class
      - com.android.settings:string/other_gestures_category_title
      - com.android.settings:string/setup_fingerprint_enroll_finish_message
      - com.android.settings:string/suggested_fingerprint_lock_settings_summary
      - com.android.settings:string-array/config_settings_slices_accessibility_components
      - com.android.settings:string-array/slice_allowlist_package_names
      - com.android.systemui:bool/config_hspa_data_distinguishable
      - com.android.systemui:bool/config_touch_context_enabled
      - com.android.systemui:bool/config_wlc_support_enabled
      - com.android.systemui:drawable/ic_qs_branded_vpn
      - com.android.systemui:drawable/stat_sys_branded_vpn
      - com.android.systemui:string/config_dockComponent
      - com.android.systemui:string/config_screenshotEditor
      - com.android.systemui:string-array/config_controlsPreferredPackages
      - com.android.traceur:bool/config_hspa_data_distinguishable
      - com.google.android.networkstack/NetworkStackConfig:bool/config_dhcp_client_hostname
      - com.google.android.permissioncontroller/PermissionControllerStyles:string/help_app_permissions
      - com.google.android.pixel.setupwizard:bool/show_air_gestures_opt_in
      - com.google.android.pixel.setupwizard/PixelSetupWizard:string/exit_to_action_in_initial_setup
      - com.google.android.pixel.setupwizard/PixelSetupWizard:string-array/deferred_medium_priority_actions

    prefix:
      - android:bool/config_assist
      - android:drawable/ic_doc_
      - android:string-array/config_companionDevice
      - android:string/biometric_
      - android:string/config_system
      - android:string/widget_
      - android:string/config_bodyFont
      - android:string/config_feedbackIntent
      - android:string/config_headlineFont
      - android:string/config_helpIntent
      - android:string/config_helpPackage
      - com.android.managedprovisioning
      - com.android.providers.settings
      - com.android.simappdialog
      - com.android.settings:bool/config_
      - com.android.settings:drawable/aware_
      - com.android.settings:drawable/$aware_
      - com.android.settings:string/ambient_display_wake_screen_
      - com.android.settings:string/aware_
      - com.android.systemui:string/branded_
      - com.android.settings:string/dialog_aware_
      - com.android.settings:string/display_white_balance_
      - com.android.settings:string/fingerprint_
      - com.android.settings:string/gesture_
      - com.android.settings:string/keywords_
      - com.android.settings:string/lock_settings_
      - com.android.settings:string/security_settings_
      - com.android.settings:string/tips_help_url_
      - com.android.settings:string/unlock_disable_frp_
      - com.android.settings:string/wake_screen_
      - com.android.wifi.resources/WifiCustomization:integer/config_wifi_framework_wifi_score_
      - com.google.android.cellbroadcastreceiver
      - com.google.android.cellbroadcastservice
      - com.google.android.documentsui
      - com.google.android.flipendo

    regex:
      - '^com\.google\.android\.pixel\.setupwizard/PixelSetupWizard:string/setup_.+_font_family$'

    substring:
      - elmyra

  presigned:
    match:
      - product/app/arcore/arcore.apk
      - product/app/CalculatorGooglePrebuilt/CalculatorGooglePrebuilt.apk
      - product/app/CalendarGooglePrebuilt/CalendarGooglePrebuilt.apk
      - product/app/Chrome-Stub/Chrome-Stub.apk
      - product/app/DevicePolicyPrebuilt/DevicePolicyPrebuilt.apk
      - product/app/Drive/Drive.apk
      - product/app/GoogleContacts/GoogleContacts.apk
      - product/app/GoogleTTS/GoogleTTS.apk
      - product/app/LatinIMEGooglePrebuilt/LatinIMEGooglePrebuilt.apk
      - product/app/Maps/Maps.apk
      - product/app/Photos/Photos.apk
      - product/app/PrebuiltDeskClockGoogle/PrebuiltDeskClockGoogle.apk
      - product/app/PrebuiltGmail/PrebuiltGmail.apk
      - product/app/SoundPickerPrebuilt/SoundPickerPrebuilt.apk
      - product/app/talkback/talkback.apk
      - product/app/Videos/Videos.apk
      - product/app/VoiceAccessPrebuilt/VoiceAccessPrebuilt.apk
      - product/app/WebViewGoogle-Stub/WebViewGoogle-Stub.apk
      - product/app/YouTube/YouTube.apk
      - product/app/YouTubeMusicPrebuilt/YouTubeMusicPrebuilt.apk
      - product/priv-app/AndroidAutoStubPrebuilt/AndroidAutoStubPrebuilt.apk
      - product/priv-app/AmbientStreaming/AmbientStreaming.apk
      - product/priv-app/CarrierServices/CarrierServices.apk
      - product/priv-app/DeviceIntelligenceNetworkPrebuilt/DeviceIntelligenceNetworkPrebuilt.apk
      - product/priv-app/DreamlinerPrebuilt/DreamlinerPrebuilt.apk
      - product/priv-app/EuiccGoogle/EuiccGoogle.apk
      - product/priv-app/FilesPrebuilt/FilesPrebuilt.apk
      - product/priv-app/GCS/GCS.apk
      - product/priv-app/GoogleCamera/GoogleCamera.apk
      - product/priv-app/GoogleDialer/GoogleDialer.apk
      - product/priv-app/GoogleRestorePrebuilt/GoogleRestorePrebuilt.apk
      - product/priv-app/HelpRtcPrebuilt/HelpRtcPrebuilt.apk
      - product/priv-app/MaestroPrebuilt/MaestroPrebuilt.apk
      - product/priv-app/OdadPrebuilt/OdadPrebuilt.apk
      - product/priv-app/Phonesky/Phonesky.apk
      - product/priv-app/PixelLiveWallpaperPrebuilt/PixelLiveWallpaperPrebuilt.apk
      - product/priv-app/PrebuiltBugle/PrebuiltBugle.apk
      - product/priv-app/PrebuiltGmsCore/PrebuiltGmsCoreSc.apk
      - product/priv-app/RecorderPrebuilt/RecorderPrebuilt.apk
      - product/priv-app/SafetyHubPrebuilt/SafetyHubPrebuilt.apk
      - product/priv-app/SCONE/SCONE.apk
      - product/priv-app/ScribePrebuilt/ScribePrebuilt.apk
      - product/priv-app/SecurityHubPrebuilt/SecurityHubPrebuilt.apk
      - product/priv-app/SettingsIntelligenceGooglePrebuilt/SettingsIntelligenceGooglePrebuilt.apk
      - product/priv-app/TipsPrebuilt/TipsPrebuilt.apk
      - product/priv-app/TurboPrebuilt/TurboPrebuilt.apk
      - product/priv-app/Velvet/Velvet.apk
      - product/priv-app/WellbeingPrebuilt/WellbeingPrebuilt.apk
      - system/app/CaptivePortalLoginGoogle/CaptivePortalLoginGoogle.apk
      - system/priv-app/DocumentsUIGoogle/DocumentsUIGoogle.apk
      - system/priv-app/NetworkStackGoogle/NetworkStackGoogle.apk
      - system_ext/priv-app/EuiccSupportPixel/EuiccSupportPixel.apk
      - system_ext/priv-app/EuiccSupportPixelPermissions/EuiccSupportPixelPermissions.apk

    prefix:
      - product/app/PixelCameraServices
      - product/priv-app/DevicePersonalizationPrebuiltPixel

  props:
    match:
      - debug.sf.enable_egl_image_tracker
      - keyguard.no_require_sim
      - ro.apex.updatable
      - ro.boot.vendor.overlay.theme
      - ro.com.android.prov_mobiledata
      - ro.control_privapp_permissions
      - ro.llkd.enable
      - ro.surface_flinger.supports_background_blur
      - ro.vendor.aware_available

    prefix:
      - log.tag.

  sepolicy_dirs:
    match:
      - device/google/gs101-sepolicy/whitechapel/vendor/google
      - hardware/google/pixel-sepolicy/flipendo
      - hardware/google/pixel-sepolicy/googlebattery
      - hardware/google/pixel-sepolicy/ramdump
      - hardware/google/pixel-sepolicy/sota_app/system_ext
      - hardware/google/pixel-sepolicy/turbo_adapter

includes:
  - ../../snippets/gms.yml
  - ../../snippets/mainline_system.yml

platform:
  sepolicy_dirs:
    - hardware/google/pixel-sepolicy
